
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ffmpeg?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: spirit
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
# ===========================================================================================
logging.level.ROOT: INFO
logging.level.org.springframework.web: INFO
logging.level.cn.com.waterelephant: INFO

logging.path: /Users/admin/logs/backup
logging.file: /Users/admin/logs/media/${spring.application.name}.log

logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %-5level %logger{36} - %msg%n'
